### PR TITLE
Convert to dep from glide

### PR DESCRIPTION
**Pull request by philoserf**
offered as a replacement for pr/#18

---
This change is [Reviewable](https://reviewable.io/reviews/samsung-cnct/container-technical-on-boarding/19)

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Please review and comment on the original PR. 

This is neither in the spirit of acknowledging a team member's work, nor does it offer the team member a chance to improve on their work if nevessary.

**Comment by philoserf** [comment]
I did. Please review my comments to your PR.

**Comment by philoserf** [comment]
I found it easier to create an alternative. You can see the PR I offered to your PR. I created that before I created this.

**Comment by joejulian** [comment]
All the pitfalls @guineveresaenger and I worked through and solved yesterday in #18 are in this PR. I suggest we just close this.

**Comment by philoserf** [comment]
I see that. I was trying to move it forward.

**Pull request closed without merging**
