### PR TITLE
Migration to dep

### PR DESCRIPTION
**Pull request by guineveresaenger**
This is a second attempt to migrate from glide to dep, as that is the current standard for Golang dependency management.

This PR is opened as an improvement on #17.

### CODE REVIEW

**Comment by philoserf** [comment]
So to renew the conversation here. the archival directory built by one of the `dep` runs needs to be removed.

`_vendor-20180319145940/`

**Comment by philoserf** [comment]
Not sure what heppened but a second run on my local copy after removing `_vendor-20180319145940/` does not change `vendor/github.com/revel/modules/static/`

I think this is ready once the `_vendor` is removed

**Comment by philoserf** [comment]
advisory: not a blocker to approval

```yaml
...
[prune]
  go-tests = true
  unused-packages = true
  non-go = true
...

adding non-go = true to `Gopkg.toml` saves us some more vendor directory noise. I think it should be our standard. the option was added to dep but not to the dep generated Gopkg.toml

All the following go away.

```plain
deleted:    vendor/github.com/agtorre/gocolorize/.gitignore
	deleted:    vendor/github.com/agtorre/gocolorize/README.md
	deleted:    vendor/github.com/agtorre/gocolorize/wercker.yml
	deleted:    vendor/github.com/golang/protobuf/proto/Makefile
	deleted:    vendor/github.com/klauspost/cpuid/.gitignore
	deleted:    vendor/github.com/klauspost/cpuid/.travis.yml
	deleted:    vendor/github.com/klauspost/cpuid/CONTRIBUTING.txt
	deleted:    vendor/github.com/klauspost/cpuid/README.md
	deleted:    vendor/github.com/masterminds/semver/.travis.yml
	deleted:    vendor/github.com/masterminds/semver/CHANGELOG.md
	deleted:    vendor/github.com/masterminds/semver/Makefile
	deleted:    vendor/github.com/masterminds/semver/README.md
	deleted:    vendor/github.com/masterminds/semver/appveyor.yml
	deleted:    vendor/github.com/revel/config/README.md
	deleted:    vendor/github.com/revel/cron/.gitignore
	deleted:    vendor/github.com/revel/cron/.travis.yml
	deleted:    vendor/github.com/revel/cron/README.md
	deleted:    vendor/github.com/revel/modules/testrunner/app/views/TestRunner/FailureDetail.html
	deleted:    vendor/github.com/revel/modules/testrunner/app/views/TestRunner/Index.html
	deleted:    vendor/github.com/revel/modules/testrunner/app/views/TestRunner/SuiteResult.html
	deleted:    vendor/github.com/revel/modules/testrunner/conf/routes
	deleted:    vendor/github.com/revel/modules/testrunner/public/css/bootstrap.min.css
	deleted:    vendor/github.com/revel/modules/testrunner/public/css/github.css
	deleted:    vendor/github.com/revel/modules/testrunner/public/images/favicon.png
	deleted:    vendor/github.com/revel/modules/testrunner/public/js/bootstrap.min.js
	deleted:    vendor/github.com/revel/modules/testrunner/public/js/highlight.pack.js
	deleted:    vendor/github.com/revel/modules/testrunner/public/js/jquery-1.9.1.min.js
	deleted:    vendor/github.com/revel/revel/.gitignore
	deleted:    vendor/github.com/revel/revel/.travis.yml
	deleted:    vendor/github.com/revel/revel/CHANGELOG.md
	deleted:    vendor/github.com/revel/revel/CONTRIBUTING.md
	deleted:    vendor/github.com/revel/revel/README.md
	deleted:    vendor/github.com/revel/revel/README.md.orig
	deleted:    vendor/github.com/revel/revel/version.go.orig
	deleted:    vendor/github.com/satori/go.uuid/.travis.yml
	deleted:    vendor/github.com/satori/go.uuid/README.md
	deleted:    vendor/golang.org/x/oauth2/.travis.yml
	deleted:    vendor/golang.org/x/oauth2/CONTRIBUTING.md
	deleted:    vendor/golang.org/x/oauth2/README.md
	deleted:    vendor/golang.org/x/sys/unix/.gitignore
	deleted:    vendor/golang.org/x/sys/unix/README.md
	deleted:    vendor/golang.org/x/sys/unix/mkall.sh
	deleted:    vendor/golang.org/x/sys/unix/mkerrors.sh
	deleted:    vendor/golang.org/x/sys/unix/mksyscall.pl
	deleted:    vendor/golang.org/x/sys/unix/mksyscall_solaris.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysctl_openbsd.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysnum_darwin.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysnum_dragonfly.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysnum_freebsd.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysnum_netbsd.pl
	deleted:    vendor/golang.org/x/sys/unix/mksysnum_openbsd.pl
	deleted:    vendor/google.golang.org/appengine/internal/base/api_base.proto
	deleted:    vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
	deleted:    vendor/google.golang.org/appengine/internal/log/log_service.proto
	deleted:    vendor/google.golang.org/appengine/internal/regen.sh
	deleted:    vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
	deleted:    vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/.editorconfig
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/.gitignore
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/.travis.yml
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/CHANGELOG.md
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/CONTRIBUTING.md
	deleted:    vendor/gopkg.in/fsnotify/fsnotify.v1/README.md
	deleted:    vendor/gopkg.in/yaml.v2/.travis.yml
	deleted:    vendor/gopkg.in/yaml.v2/README.md
```

**Comment by guineveresaenger** [comment]
I misunderstood about the `_vendor-12345...` folder. I used `git-filter-branch` to remove it permanently. It... looks like it went too far back in history so I might try something else.

**Comment by guineveresaenger** [comment]
I suspect there is a bug in MilestoneDueTime that makes that particulat test flaky.

I attempted some changes this weekend, and then force pushed back to the _exact same commit_ that passed on Thursday, and it failed in the unit tests in CI.
These fail locally for me as well currently.

For the new implementation of this course, we may decide that we do not need a due date implementation. Time is hard!

**Comment by samba** [comment]
The test failure for `MilestoneDueTime` is a nuance of business logic. I'm exploring it to confirm, but it looks like it's going to consistently fail on Sundays. No joke. If I can confirm that, I'll post a commit to fix it.

Otherwise, this PR LGTM.

**Comment by samba** [comment]
Since CI passed earlier today (a non-Saturday), let's call this done.

I've got a solution for the `MilestoneDueTime` bug, but will reserve that for a separate PR.

**Pull request merged**
