### PR TITLE
Feat/manage dependencies

### LINKED ISSUE #12: BAC-117 ⁃ Add dependency management
Add [dep][1] to manage vendored dependencies.

[1]: https://github.com/golang/dep

### PR DESCRIPTION
**Pull request by alika**
**What this PR does / why we need it**: This PR adds dependency management (glide) to this go-lang project. This is needed to correctly manage what versions of dependent libraries are referenced and used.

**Which issue this PR fixes**: fixes #12 ([BAC-117][117])

**Verification Notes**:

The primary items to be reviewed on this is the `Makefile` and `glide.yaml`. The `Makefile` now contains a new `vendor` target that invokes [glide][1] to populate the `vendor` directory. The added vendor directory is the bulk of files changed in this PR.

You should be able to build and run the app locally by following the [in-container instructions](https://github.com/alika/container-technical-on-boarding/blob/425fc46ebcd1e5ba408c0714fb5fdb4e214636f5/README.md#running-in-container) and then opening a browsers to `http://localhost:9000`. You should see the home page for the technical-on-boarding app.

To do a live end-2-end functional test of the Github task generation triggered by the `Authorize` button on the home page you'll need a valid Github repo and associated credentials. I can provide a set of test credentials to facilitate this as needed.

[1]: https://github.com/Masterminds/glide
[117]: https://samsung-cnct.atlassian.net/browse/BAC-117

### CODE REVIEW

**Comment by leahnp** [comment]
@alika I am trying to test locally on my mac. When I run ` make docker-run` I see the following error:

```
/go/src/github.com/samsung-cnct/container-technical-on-boarding/app/jobs/onboarding/client.go:49:22: 2-valued uuid.NewV4() (value of type (github.com/satori/go.uuid.UUID, error)) where single value is expected
couldn't load packages due to errors: github.com/samsung-cnct/container-technical-on-boarding/app/jobs/onboarding
```

Do we need to add error handling to the function: `uuid.NewV4()`? Then string-ify the uuid after potential errors are processed?

**Comment by alika** [comment]
Did you receive this error when compiling the go code or during the linting process? I'm trying to reproduce the issue.

**Comment by alika** [comment]
Additionally since the dependent libraries are in the vendor directory, this code should be using `./vendor/github.com/satori/go.uuid/uuid.go` on line 462 there is:

```
462 func NewV4() UUID {
463   u := UUID{}
464   safeRandom(u[:])
465   u.SetVersion(4)
466   u.SetVariant()
467
468   return u
469 }
```

Which only has a single (1-value) return. Since the error indicates it is seeing a 2-value error, I'm worried its not using the vendored code.

**Comment by alika** [comment]
More clues: The 2-valued version of this function is on the latest master branch [here](https://github.com/satori/go.uuid/blob/36e9d2ebbde5e3f13ab2e25625fd453271d6522e/generator.go#L68). Which _should_ not be referenced in our build. This is suppose to be the job of the glide tool and associated `vendor` target in the Makefile. But perhaps the build is not referencing the vendor directory correctly.

**Comment by alika** [comment]
After some manual end-2-end testing w/@leahnp 2 issues were discovered:

1. The `docker-run-dev` in the `Makefile` is not working correctly (the `-v $(GOPATH):/go` needs to be updated)
2. There is a case in which the authenticated Github user does not have access to the target Github repo that should be accounted for and handled better.

**Comment by leahnp** [comment]
Alright - second round of testing. I am seeing the following behavior:

load: `127.0.0.1:9000`
press `authorize`
web page remains the same but url changes to: `http://toby-tester.doesnt-exist/`
press `authorize` a second time
browser updates with task creation page at: `http://toby-tester.doesnt-exist/workload` and tasks seem to be generated as expected

**Pull request merged**
